// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj2.command.SubsystemBase;
import static frc.robot.Constants.DrivetrainConstants.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.NeutralMode;
import com.kauailabs.navx.frc.AHRS;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.DriverStation;
import frc.robot.classes.Kinematics;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drivetrain extends SubsystemBase 
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX leftTalonLead;
    private WPI_TalonSRX rightTalonLead;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private boolean encodersAvailable;
    private AHRS navX;
    private Kinematics m_kinematics;
    
    public Drivetrain(Kinematics kinematics) 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        leftTalonLead = new WPI_TalonSRX(1);
        rightTalonLead = new WPI_TalonSRX(2);
        
        //Reset and calibrate the gyro
        navX = new AHRS(SPI.Port.kMXP);

        setupGyro(navX);
        enableEncoders();
        zeroDriveTrainEncoders();

        //Clearing sticky faults
        leftTalonLead.clearStickyFaults();
        leftTalonLead.clearStickyFaults();

        //Setting factory default settings to motors
        leftTalonLead.configFactoryDefault();
        rightTalonLead.configFactoryDefault();
    
        //Set motors to inverted if needed
        leftTalonLead.setInverted(false);
        rightTalonLead.setInverted(true);

        //Set encoder
        leftTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, PID_SLOT_ID, ENCODER_CONFIG_TIMEOUT_MS);
        rightTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, PID_SLOT_ID, ENCODER_CONFIG_TIMEOUT_MS);
        leftTalonLead.setSensorPhase(true);
        rightTalonLead.setSensorPhase(true);
        
        //Configure PID
        leftTalonLead.config_kF(PID_SLOT_ID, KF, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.config_kP(PID_SLOT_ID, KP, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.config_kI(PID_SLOT_ID, KI, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.config_kD(PID_SLOT_ID, KD, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.configClosedloopRamp(CLOSED_LOOP_RAMP);
        leftTalonLead.configNeutralDeadband(L_DEADBAND);
        leftTalonLead.setNeutralMode(NeutralMode.Coast);

        rightTalonLead.config_kF(PID_SLOT_ID, KF, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.config_kP(PID_SLOT_ID, KP, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.config_kI(PID_SLOT_ID, KI, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.config_kD(PID_SLOT_ID, KD, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.configClosedloopRamp(CLOSED_LOOP_RAMP);
        rightTalonLead.configNeutralDeadband(R_DEADBAND);
        rightTalonLead.setNeutralMode(NeutralMode.Coast);

        //Setup Kinematics. Kinematics is setup in robotcontainer
        m_kinematics = kinematics;
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() 
    {
        //Update Kinematics
        m_kinematics.calculatePosition(getLeftEncoderPosition(), getRightEncoderPosition());

        //Print out position information
        SmartDashboard.putNumber("X (ft)", m_kinematics.getPose().getX());
        SmartDashboard.putNumber("Y (ft)", m_kinematics.getPose().getY());
        SmartDashboard.putNumber("Heading (degrees)", m_kinematics.getPose().getHeadingDegrees());
        SmartDashboard.putNumber("NavX heading", navX.getFusedHeading());
        SmartDashboard.putNumber("Left Encoder Position", getLeftEncoderPosition());
        SmartDashboard.putNumber("Right Encoder Position", getRightEncoderPosition());
    }

    @Override
    public void simulationPeriodic() 
    {
        // This method will be called once per scheduler run when in simulation
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public double getCurrentVelocity()
    {
        double leftFeetPerSecond = controllerVelocityToFeetPerSec(leftTalonLead.getSelectedSensorVelocity(0));
        double rightFeetPerSecond = controllerVelocityToFeetPerSec(rightTalonLead.getSelectedSensorVelocity(0));
        
        return((leftFeetPerSecond + rightFeetPerSecond) / 2.0); 
    }

    public void velocityDrive(double vL, double vR)
    {
        SmartDashboard.putNumber("Velocity Left (ft/s)", vL);
        SmartDashboard.putNumber("Velocity Right (ft/s)", vR);
        leftTalonLead.set(ControlMode.Velocity, vL);
        rightTalonLead.set(ControlMode.Velocity,vR);
    }

    // Converts joystick input adjusted to a RPM for the Falcon's PIDF loop to aim for
    public void powerDrive(double leftPower, double rightPower)
    {
        double leftMotorPower = leftPower;
        double rightMotorPower = rightPower;

        //Prevent invalid input
        if( leftPower > 1.0)
        {
            leftMotorPower = 1.0;
        }

        if( leftPower < -1.0)
        {
            leftMotorPower = -1.0;
        }

        if( rightPower > 1.0)
        {
            rightMotorPower = 1.0;
        }

        if( rightPower < -1.0)
        {
            rightMotorPower = -1.0;
        }
        
        //Both left and right motor power is valid, set motor power
        leftMotorPower = leftMotorPower * MAX_VELOCITY * VELOCITY_LIMIT_PERCENTAGE;
        rightMotorPower = rightMotorPower * MAX_VELOCITY * VELOCITY_LIMIT_PERCENTAGE;

        //Set motor power
        leftTalonLead.set(ControlMode.Velocity, leftMotorPower);
        rightTalonLead.set(ControlMode.Velocity, rightMotorPower);
    }

    // Stops motor usually used after the drive command ends to prevent shenanigans
    public void stop()
    {
        leftTalonLead.set(ControlMode.Current, 0);
        rightTalonLead.set(ControlMode.Current, 0);
    }

    // Converts from encoder edges per 100 milliseconds to feet per second.
    public static double controllerVelocityToFeetPerSec(double encoderUnits) 
    {
        return controllerUnitsToFeet(encoderUnits) * SECONDS_TO_DECISEC;
    }
    
    //Converts from feet per second to encoder edges per 100 milliseconds.
    public static double feetPerSecToControllerVelocity(double feetPerSec) 
    {
        return ((feetPerSec  * GEARBOX_RATIO_TO_ONE * ENCODER_UNITS_PER_REVOLUTION) / (WHEEL_CIRCUMFERENCE_FEET)) * SECONDS_TO_DECISEC;
    }

    // Converts from encoder units to feet
    public static double controllerUnitsToFeet(double encoderUnits) 
    {
        return (encoderUnits *  WHEEL_CIRCUMFERENCE_FEET) / (GEARBOX_RATIO_TO_ONE * ENCODER_UNITS_PER_REVOLUTION);
    }

    /**
   * Attempts to enable the drivetrain encoders.
   */
    private void enableEncoders() 
    {
        encodersAvailable = 
            ((leftTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 10) == ErrorCode.OK) &&
            (rightTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 10) == ErrorCode.OK));

        if (!encodersAvailable) 
        {
            DriverStation.reportError("Failed to configure Drivetrain encoders!!", false);
        }
    }
    public boolean isEncodersAvailable() 
    {
        return encodersAvailable;
    }
    
    /**   
     * returns left encoder position
     * 
     * @return left encoder position
     */
    public double getLeftEncoderPosition() 
    {
        // Returns the number of steps, multiply by edges per step to get EPR, divided by the gearbox ratio
        return controllerUnitsToFeet(leftTalonLead.getSelectedSensorPosition(0));
    }
    
      /**
       * returns right encoder position
       * 
       * @return right encoder position
       */
    public double getRightEncoderPosition() 
    {
        // Returns the number of steps, multiply by edges per step to get EPR, divided by the gearbox ratio
        return controllerUnitsToFeet(rightTalonLead.getSelectedSensorPosition(0));    
    }
    
    private void zeroDriveTrainEncoders() 
    {
        leftTalonLead.setSelectedSensorPosition(0);
        rightTalonLead.setSelectedSensorPosition(0);
    }
      
    public double getGyroHeading() 
    {
        return (navX.getYaw() * -1.0d); // makes 0-360 fused heading from navx to -180->180
    }
    
    public void setupGyro(AHRS gyro)
    {
        System.out.println("Calibrating gyroscope.");
        gyro.enableBoardlevelYawReset(true);
        gyro.reset();
        gyro.calibrate();

        //Wait for gyro to calibrate ~1 - 10 seconds
        while (gyro.isCalibrating())
        {
        }
        
        gyro.zeroYaw();
        
        System.out.println("Calibrating gyroscope done.");
    }
}
