// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.RamseteCommand;
import edu.wpi.first.wpilibj2.command.ConditionalCommand;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import static frc.robot.Constants.DrivetrainConstants.*;
import frc.robot.Constants.TrajectoryConstants.*;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.system.plant.DCMotor;
import edu.wpi.first.wpilibj.trajectory.Trajectory;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.controller.RamseteController;

import java.util.ResourceBundle.Control;

import com.ctre.phoenix.ErrorCode;
import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.DemandType;
import com.ctre.phoenix.motorcontrol.FeedbackDevice;
import com.ctre.phoenix.motorcontrol.InvertType;
import com.ctre.phoenix.motorcontrol.NeutralMode;

import edu.wpi.first.wpilibj.Joystick;
import com.kauailabs.navx.frc.AHRS;
import edu.wpi.first.wpilibj.SPI;
import edu.wpi.first.wpilibj.I2C.Port;

import edu.wpi.first.wpilibj.kinematics.DifferentialDriveOdometry;

import edu.wpi.first.wpilibj.geometry.Pose2d;
import edu.wpi.first.wpilibj.geometry.Rotation2d;
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.DriverStation;
import frc.robot.UpdateDCMotor;
import edu.wpi.first.wpilibj.simulation.AnalogGyroSim;
import edu.wpi.first.wpilibj.simulation.DifferentialDrivetrainSim;


import edu.wpi.first.wpilibj2.command.PrintCommand;
import com.ctre.phoenix.motorcontrol.TalonSRXSimCollection;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class Drivetrain extends SubsystemBase 
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private WPI_TalonSRX leftTalonLead;
    private WPI_TalonSRX rightTalonLead;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private boolean encodersAvailable;
    private boolean useEncoders = true;
    
    private AHRS navX;
    private Pose2d savedPose;
    private final DifferentialDriveOdometry m_odometry;
    private final Field2d m_field;
    private final DifferentialDrivetrainSim m_driveSim;
    private AnalogGyro m_gyro;
    private AnalogGyroSim m_gyroSim;
    private TalonSRXSimCollection m_leftDriveSim;
    private TalonSRXSimCollection m_rightDriveSim;

    public Drivetrain() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        leftTalonLead = new WPI_TalonSRX(1);
        rightTalonLead = new WPI_TalonSRX(2);
        
        //Reset and calibrate the gyro
        navX = new AHRS(SPI.Port.kMXP);

        setupGyro(navX);
        resetEncoders();

        //Instantiating Drivetrain Odometry as NavX heading
        m_odometry = new DifferentialDriveOdometry(Rotation2d.fromDegrees(getGyroHeading())); 

        //Adding Field2d to send "field" data to simluation
        m_field = new Field2d();
        SmartDashboard.putData("Field",m_field);

        //Instantiating riveSimulation
        m_driveSim = new DifferentialDrivetrainSim(
            UpdateDCMotor.getHDHex(1), // Don't need to extend could just create a local DCMotor 
            20., // Gear Ratio
            4., //Moment of Inertia (Not Correct) (m/s^2)
            15., //Mass of robot (Not Correct) (kg)
            0.0381, //Wheel radius (m)
            TRACK_WIDTH_METERS,
            null //Standard deviations for noise ect doesn't need to be added yet
        );

        m_gyro = new AnalogGyro(1);
        m_gyroSim = new AnalogGyroSim(m_gyro);
        m_leftDriveSim = leftTalonLead.getSimCollection();
        m_rightDriveSim = rightTalonLead.getSimCollection();


        //Clearing sticky faults
        leftTalonLead.clearStickyFaults();
        leftTalonLead.clearStickyFaults();

        //Setting factory default settings to motors
        leftTalonLead.configFactoryDefault();
        rightTalonLead.configFactoryDefault();
    
        //Set motors to inverted if needed
        leftTalonLead.setInverted(false);
        rightTalonLead.setInverted(true);

        //Set encoder
        leftTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, PID_SLOT_ID, ENCODER_CONFIG_TIMEOUT_MS);
        rightTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, PID_SLOT_ID, ENCODER_CONFIG_TIMEOUT_MS);
        leftTalonLead.setSensorPhase(true);
        rightTalonLead.setSensorPhase(true);
        
        //Configure PID
        leftTalonLead.config_kF(PID_SLOT_ID, KF, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.config_kP(PID_SLOT_ID, KP, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.config_kI(PID_SLOT_ID, KI, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.config_kD(PID_SLOT_ID, KD, PID_CONFIG_TIMEOUT_MS);
        leftTalonLead.configClosedloopRamp(CLOSED_LOOP_RAMP);
        leftTalonLead.configNeutralDeadband(L_DEADBAND);
        leftTalonLead.setNeutralMode(NeutralMode.Coast);

        rightTalonLead.config_kF(PID_SLOT_ID, KF, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.config_kP(PID_SLOT_ID, KP, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.config_kI(PID_SLOT_ID, KI, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.config_kD(PID_SLOT_ID, KD, PID_CONFIG_TIMEOUT_MS);
        rightTalonLead.configClosedloopRamp(CLOSED_LOOP_RAMP);
        rightTalonLead.configNeutralDeadband(R_DEADBAND);
        rightTalonLead.setNeutralMode(NeutralMode.Coast);
        
        enableEncoders();
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        m_odometry.update(
            Rotation2d.fromDegrees(getGyroHeading()),
                edgesToMeters(getLeftEncoderPosition()),
                edgesToMeters(getRightEncoderPosition())
        );

        SmartDashboard.putNumber("Gyro heading", navX.getAngle());
        SmartDashboard.putNumber("Yaw val", navX.getYaw());
        SmartDashboard.putNumber("TranslationX", m_odometry.getPoseMeters().getTranslation().getX());
        SmartDashboard.putNumber("TranslationY", m_odometry.getPoseMeters().getTranslation().getY());
        SmartDashboard.putNumber("Left Encoder Position", getLeftEncoderPosition());
        SmartDashboard.putNumber("Right Encoder Position", getRightEncoderPosition());

        //Updating robot Geometry on field simulation
        m_field.setRobotPose(getCurrentPose());

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    // Converts joystick input adjusted for deadband to current for the motor
    public void dumbDrive(double leftPos, double rightPos) 
    {
        double leftMotorPower = 0.0;
        double rightMotorPower = 0.0;

        // Running at half speed as to not kill people
        leftMotorPower = calcMotorPower(leftPos, L_DEADBAND);
        rightMotorPower = calcMotorPower(rightPos, R_DEADBAND);

        if((INVALID_INPUT == leftMotorPower) || (INVALID_INPUT == rightMotorPower))
        {
            System.out.println("Invalid motor input! Left motor: " + leftPos + "Right motor: " + rightPos);
            //Motor power is invalid! Stop all motors
            stop();
        }
        else
        {
            //Both left and right motor power is valid, set motor power
            leftTalonLead.set(ControlMode.PercentOutput, leftMotorPower * VELOCITY_LIMIT_PERCENTAGE);
            rightTalonLead.set(ControlMode.PercentOutput, rightMotorPower * VELOCITY_LIMIT_PERCENTAGE);
        }
    }

    // Converts joystick input adjusted to a RPM for the Falcon's PIDF loop to aim for
    public void velocityDrive(double leftPos, double rightPos, boolean useSlowModifier, boolean useReverse)
    {
        double leftMotorPower = 0.0;
        double rightMotorPower = 0.0;
        
        //Reverse motor positions if needed
        if(useReverse)
        {     
            double temp = leftPos;
            leftPos = -rightPos;
            rightPos = -temp;
        }

        //Calculate Motor Power
        leftMotorPower = calcMotorPower(leftPos, L_DEADBAND);
        rightMotorPower = calcMotorPower(rightPos, R_DEADBAND);
        
        // Checking if motor values are valid
        if ((INVALID_INPUT == leftMotorPower) || (INVALID_INPUT == rightMotorPower))
        {
            System.out.println("Invalid motor input! Left motor: " + leftPos + "Right motor: " + rightPos);
            //Motor power is invalid! Stop all motors
            stop();
        }
        else
        {
            //Both left and right motor power is valid, set motor power
            leftMotorPower = leftMotorPower * MAX_VELOCITY * VELOCITY_LIMIT_PERCENTAGE;
            rightMotorPower = rightMotorPower * MAX_VELOCITY * VELOCITY_LIMIT_PERCENTAGE;

            if(useSlowModifier)
            {
                leftMotorPower = leftMotorPower * VELOCITY_SLOWDOWN_MODIFIER;
                rightMotorPower = rightMotorPower * VELOCITY_SLOWDOWN_MODIFIER;
            }

            //Set motor power
            leftTalonLead.set(ControlMode.Velocity, leftMotorPower);
            rightTalonLead.set(ControlMode.Velocity, rightMotorPower);
        }
    }

    // Stops motor usually used after the drive command ends to prevent shenanigans
    public void stop()
    {
        leftTalonLead.set(ControlMode.Current, 0);
        rightTalonLead.set(ControlMode.Current, 0);
    }

    /* Calculates the motor power to use based on a given deadband and 
    *  joystick input from -1 to 1
    *  Prevents spikes in motor power by calculating the line to use 
    *  where 0 is the deadband and 1 is the max */
    public double calcMotorPower(double input, double deadband)
    {
        double retval = 0.0;

        //input must be between -1 and 1
        if((input < -1) ||  (input > 1))
        { 
            retval = INVALID_INPUT;
        }
        //Check if input is inside the deadband
        else if(Math.abs(input) <= deadband) 
        { 
            retval = 0.0;
        } 
        //Input is valid and NOT in the deadband
        else 
        { 
            retval = (Math.abs(input) - deadband)/(1 - deadband);
            if(input < 0) 
            { 
                //Input is negative
                retval = -1 * retval;
            } 
        }
        
        return retval;
    }

    //Velocity Drive without Deadband for vision purposes
    public void visionDrive(double leftPos, double rightPos)
    {
        if (leftPos > 1 || leftPos < -1 || rightPos > 1 || rightPos < -1)
        {
            //Position is invalid!
            System.out.println("Invalid motor input! Left motor: " + leftPos + "Right motor: " + rightPos);
            //Stop all motors
            stop();
        } 
        //Position is valid, set motors
        else 
        {
            leftTalonLead.set(ControlMode.Velocity,(leftPos * MAX_VELOCITY));
            rightTalonLead.set(ControlMode.Velocity,(rightPos * MAX_VELOCITY));
        }
    }

    //The velocity drive function used for autonav, it arbitrarily adds a FeedForward to the existing PID using kV,kA and kS
    public void autoDriveVelocity(double leftVelocity, double rightVelocity)
    {
        var leftDriveVolts = FEED_FORWARD.calculate(leftVelocity);
        var rightDriveVolts = FEED_FORWARD.calculate(rightVelocity);

        leftTalonLead.set(
            ControlMode.Velocity,
            metersPerSecToEdgesPerDecisec(leftVelocity),
            DemandType.ArbitraryFeedForward,
            (leftDriveVolts / 12)
        );

        rightTalonLead.set(
            ControlMode.Velocity,
            metersPerSecToEdgesPerDecisec(rightVelocity),
            DemandType.ArbitraryFeedForward,
            (rightDriveVolts / 12)
        );
    }

    //Returns encoder clicks to meters used for getting distance travelled
    public static double edgesToMeters(double clicks)
    {
        return (WHEEL_CIRCUMFERENCE_METERS / ENCODER_EPR) * clicks; 
    }
    // Converts from encoder edges per 100 milliseconds to meters per second.
    public static double edgesPerDecisecToMetersPerSec(double stepsPerDecisec) 
    {
        return edgesToMeters(stepsPerDecisec * 10);
    }
    //Converts from meters per second to encoder edges per 100 milliseconds.
    public static double metersPerSecToEdgesPerDecisec(double metersPerSec) 
    {
        return metersToEdges(metersPerSec) * 0.1d;
    }

    //Converts from meters to encoder edges
    public static double metersToEdges(double meters)
    {
        return (meters/ WHEEL_CIRCUMFERENCE_METERS) * 0.1d;
    }

    public Command createRamseteController(Trajectory trajectory) 
    {
        return new ConditionalCommand(
            new RamseteCommand(trajectory, 
                            this::getCurrentPose, 
                            new RamseteController(RAMSETE_B,RAMSETE_ZETA), 
                            DRIVE_KINEMATICS, 
                            this::autoDriveVelocity, 
                            this),
            new PrintCommand("Cannot run trajectory because encoders are unavailable!!"), 
                            this::isEncodersAvailable); 
    }
    
      /**
   * Handles changing the "Use encoders" entry to retry enabling encoders if they failed previously.
   * @param notification network table entry notification
   */
   /* 
   private void handleEncoderEntry(EntryNotification notification) { //Currently not being used
        var entry = notification.getEntry();
        if(entry.getBoolean(true) && (!encodersAvailable || !useEncoders)) {
        useEncoders = true;
        enableEncoders();
        } else if (!entry.getBoolean(true)) {
        useEncoders = false;
        }
        entry.setBoolean(useEncoders);
    }
    */
    /**
   * Attempts to enable the drivetrain encoders.
   */
    private void enableEncoders() 
    {
        encodersAvailable = 
            ((leftTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 10) == ErrorCode.OK) &&
            (rightTalonLead.configSelectedFeedbackSensor(FeedbackDevice.QuadEncoder, 0, 10) == ErrorCode.OK));

        if (!encodersAvailable) 
        {
            DriverStation.reportError("Failed to configure Drivetrain encoders!!", false);
            useEncoders = false;
        }
    }
    public boolean isEncodersAvailable() 
    {
        return encodersAvailable;
    }
    
      /**   
       * returns left encoder position
       * 
       * @return left encoder position
       */
    public double getLeftEncoderPosition() 
    {
        // Returns the number of steps, multiply by edges per step to get EPR, divided by the gearbox ratio
        return (leftTalonLead.getSelectedSensorPosition(0) * ENCODER_EDGES_PER_STEP) / GEARBOX_RATIO_TO_ONE;
    }
    
      /**
       * returns right encoder position
       * 
       * @return right encoder position
       */
    public double getRightEncoderPosition() 
    {
        // Returns the number of steps, multiply by edges per step to get EPR, divided by the gearbox ratio
        return (rightTalonLead.getSelectedSensorPosition(0) * ENCODER_EDGES_PER_STEP) / GEARBOX_RATIO_TO_ONE;
    }
    
    private void zeroDriveTrainEncoders() 
    {
        leftTalonLead.setSelectedSensorPosition(0);
        rightTalonLead.setSelectedSensorPosition(0);
    }
      
    public double getGyroHeading() 
    {
        return (navX.getYaw() * -1.0d); // makes 0-360 fused heading from navx to -180->180
    }

    public Pose2d getCurrentPose() 
    {
        return m_odometry.getPoseMeters();
    }

    public void resetOdometry(Pose2d pose) 
    {
        resetEncoders();
        m_odometry.resetPosition(pose, new Rotation2d(getGyroHeading()));
      }
    
      /**
       * Resets the current pose to the specified pose. This this ONLY be called
       * when the robot's position on the field is known, like at the beginnig of
       * a match. This will also reset the saved pose since the old pose could be invalidated.
       * @param newPose new pose
       */
    public void setCurrentPose(Pose2d newPose) 
    {
        zeroDriveTrainEncoders();
        savedPose = newPose;
        m_odometry.resetPosition(newPose, Rotation2d.fromDegrees(getGyroHeading()));
    }

    public void resetEncoders()
    {
        leftTalonLead.setSelectedSensorPosition(0);
        rightTalonLead.setSelectedSensorPosition(0);
    }
    public void setupGyro(AHRS gyro)
    {
        System.out.println("Calibrating gyroscope.");
        gyro.enableBoardlevelYawReset(true);
        gyro.reset();
        gyro.calibrate();

        //Wait for gyro to calibrate ~1 - 10 seconds
        while (gyro.isCalibrating())
        {
        }
        
        gyro.zeroYaw();
        
        System.out.println("Calibrating gyroscope done.");
    }
}
