// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.classes.Position2D;
import frc.robot.classes.TargetPosition2D;
import frc.robot.classes.SmoothControl;
import frc.robot.subsystems.Drivetrain;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import static frc.robot.Constants.DrivetrainConstants.*;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutonomousCommand extends CommandBase 
{
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private SmoothControl m_smoothControl;
    private TargetPosition2D m_currentTargetPose;
    private Drivetrain m_drivetrain;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    public AutonomousCommand(Drivetrain drivetrain) 
    {
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_drivetrain = drivetrain;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() 
    {
        m_currentTargetPose = new TargetPosition2D(3.0, 3.0, -90.0, -4);
        //For testing!
        //Robot Pos: [0, 0, 0]; target pos: [3, 3, 90], Vel: 4 gives: Range: 4.2426, w_des: 1.4176
        //Robot Pos: [0, 0, 0]; target pos: [3, 3, -90]; Vel: -4 gives: Range: 4.2426, w_des: 6.2974
        m_smoothControl = new SmoothControl();
        m_smoothControl.setNextTarget((Position2D)m_currentTargetPose);  // test values
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() 
    {
        double vR = 0.0;
        double vL = 0.0;
        m_smoothControl.computeTurnRate(m_drivetrain.getCurrentPose(), -4.0);
        //m_smoothControl.computeTurnRate(m_drivetrain.getCurrentPose(), m_drivetrain.getCurrentVelocity());
        //Calculate vR
        vR = m_currentTargetPose.getVelocity() + (TRACK_WIDTH_FEET/2)*m_smoothControl.getTurnRate();
        //Calculate vL
        vL = m_currentTargetPose.getVelocity() - (TRACK_WIDTH_FEET/2)*m_smoothControl.getTurnRate();
        //Send vR and vL to velocity drive
        m_drivetrain.velocityDrive(vL, vR);

        SmartDashboard.putNumber("vR", vR);
        SmartDashboard.putNumber("vL", vL);
        //Done.
        SmartDashboard.putNumber("Range", m_smoothControl.getRange());
        SmartDashboard.putNumber("Turn Rate", m_smoothControl.getTurnRate());
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) 
    {
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() 
    {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() 
    {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
